Add Spark questions
nnstu-appmath/Spark pull request #27
Opened 2023-01-15 00:49 UTC by ArapovXD

[issue#25](https://github.com/nnstu-appmath/Spark/issues/25)

2023-01-15 15:00 UTC, arybin93 requested changes
Спасибо, оставил комментарии которые нужно учесть)

2023-01-15 15:00 UTC, arybin93 commented on questions.md
> +8. Назовите основные отличия Hadoop и Spark
Тут, наверное, имеет ввиду Hadoop MapReduce?

2023-01-15 15:00 UTC, arybin93 commented on questions.md
> +5. Какую функцию выполняет Spark Core?
Может ещё добавить вопрос, про какие языки поддерживает Spark?

2023-01-15 15:57 UTC, ArapovXD commented on questions.md
> +8. Назовите основные отличия Hadoop и Spark
Про скорость обработки данных, пакетную и рил тайм обработку

2023-01-15 15:57 UTC, ArapovXD commented on questions.md
> +5. Какую функцию выполняет Spark Core?
Добавил

2023-01-15 16:02 UTC, braindeadboooooy approved these changes
Хорошие вопросы, позволяющие лучше проработать материал!

2023-01-15 16:32 UTC, another-weasley approved these changes
Вопросы хорошие, в принципе охватывают весь материал по Spark.

2023-01-16 16:05 UTC, Boriskova27 approved these changes
Хорошие вопросы, охватывающие тему

2023-01-16 17:07 UTC, arybin93 commented on questions.md
> +8. Назовите основные отличия Hadoop и Spark
Да, про отличия понятно. Просто в Hadoop пакетной обработкой модуль MapReduce занимается. Поэтому логичнее спрашивать разницу между Hadoop MR и Spark)

2023-01-16 18:28 UTC, ArapovXD commented on questions.md
> +8. Назовите основные отличия Hadoop и Spark
> Да, про отличия понятно. Просто в Hadoop пакетной обработкой модуль MapReduce занимается. Поэтому логичнее спрашивать разницу между Hadoop MR и Spark)

Изменил формулировку вопроса

2023-01-17 18:03 UTC, merged