added spark use cases
nnstu-appmath/Spark pull request #4
Opened 2022-09-24 13:31 UTC by krozybaeva

2022-09-26 10:15 UTC, Schepetova approved these changes
Все классно, молодец!

2022-09-29 06:25 UTC, arybin93 requested changes
Спасибо за материал, добавил один комментарий.

2022-09-29 06:25 UTC, arybin93 commented on spark.md
> +**Apache Spark на TripAdvisor:** TripAdvisor помогает пользователям планировать свои поездки, используя возможности Apache Spark. Он помогает пользователям с рекомендациями по ценам, запрашивая у тыс
Хорошо бы добавить источники, которые использовались. Что думаешь?

2022-09-29 16:06 UTC, krozybaeva commented on spark.md
> +**Apache Spark на TripAdvisor:** TripAdvisor помогает пользователям планировать свои поездки, используя возможности Apache Spark. Он помогает пользователям с рекомендациями по ценам, запрашивая у тыс
Хорошо, добавлю!

2022-09-29 18:21 UTC, g1ease commented
хорошие примеры! все понятно и доступно!

2022-09-29 18:29 UTC, g1ease commented on spark.md
> +**Apache Spark на TripAdvisor:** TripAdvisor помогает пользователям планировать свои поездки, используя возможности Apache Spark. Он помогает пользователям с рекомендациями по ценам, запрашивая у тыс
хорошие примеры! все понятно и доступно!

2022-09-29 18:43 UTC, g1ease approved these changes
хорошие примеры! все понятно и доступно!

2022-09-29 19:01 UTC, g1ease approved these changes

2022-09-30 07:59 UTC, arybin93 approved these changes
Спасибо за работу

2022-09-30 10:29 UTC, merged