added history of spark
nnstu-appmath/Spark pull request #8
Opened 2022-10-04 19:29 UTC by g1ease

Добавила материал "История Spark". Жду ваших комментариев!

2022-10-05 16:44 UTC, Schepetova approved these changes

2022-10-06 03:29 UTC, krozybaeva approved these changes
Great job!

2022-10-07 15:40 UTC, ArapovXD approved these changes
woOwo w o

2022-10-09 17:55 UTC, arybin93 requested changes
Спасибо за работу, несколько общих моментов:
1. Пока в этом репозитории не было добавлено ни одного issue. Мы вроде бы договорились вести работу через создание issue и там описать примерно, что нужно сделать)
2. Название бранча не соответствует нашему соглашению, если вы в рамках репозитория используете другое, опишите его в readme. Или приведите к общему.
3. Историю Spark-а в таком кратком виде, в целом можно было бы объединить в какой-нибудь один блок типа "Введение в Spark" (один markdown файл).
Где добавить информацию, что это такое, краткая история, зачем нужно и где применяется, общая архитектура. Для того чтобы вести работу параллельно, подход с разными файлами подходит, но подумайте, чтобы потом разные файлы объединить в один.
4. Проверить кодировку, GitHub некорректно отображает в режиме review

2022-10-09 17:55 UTC, arybin93 commented on History of Spark.md
> +�������� ����� *Apache Spark* � ��������-��������� ������ � ������� ����������� **����� �������** (����. *Matei Zaharia*), ����� ������ ��� �������� � 2009 ����, ������ ���������� ������������ ������
Это только у меня так?
![image](https://user-images.githubusercontent.com/6921551/194771436-fe4e5666-3e72-48a6-aa8c-e3ee8d6534de.png)
Как будто проблемы с кодировкой... надо перепроверить.

2022-10-09 17:58 UTC, arybin93 commented on History of Spark.md
> +�������� ����� *Apache Spark* � ��������-��������� ������ � ������� ����������� **����� �������** (����. *Matei Zaharia*), ����� ������ ��� �������� � 2009 ����, ������ ���������� ������������ ������
Видимо какой-то глюк GitHub-а

2022-10-09 18:52 UTC, g1ease commented on History of Spark.md
> +�������� ����� *Apache Spark* � ��������-��������� ������ � ������� ����������� **����� �������** (����. *Matei Zaharia*), ����� ������ ��� �������� � 2009 ����, ������ ���������� ������������ ������
не знаю, что не так с кодировкой, но посмотрю. спасибо
![изображение](https://user-images.githubusercontent.com/62951698/194774366-c2cb45be-702c-41df-920e-9b52e5277b15.png)

2022-10-10 01:13 UTC, closed without merging